networks:
  development:
volumes:
  db_data:
  gem_cache:
  node_modules:
services:
  db:
    image: postgres:16.3
    container_name: shore_db
    networks:
      - development
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - development
    container_name: shore_app
    stdin_open: true
    tty: true
    entrypoint: docker-entrypoint.sh
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - RAILS_SERVE_STATIC_FILES=false
      - VITE_RUBY_HOST=vite
    volumes:
      - .:/var/app:cached
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/var/app/node_modules
    depends_on:
      - db
    command: bundle exec rails s -b 0.0.0.0 -p 3000
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - development
    container_name: shore_worker
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - RAILS_SERVE_STATIC_FILES=false
    volumes:
      - .:/var/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/var/app/node_modules
    depends_on:
      - db
    command: bundle exec rake solid_queue:start
  vite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shore_vite
    networks:
      - development
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - RAILS_SERVE_STATIC_FILES=false
      - VITE_RUBY_HOST=0.0.0.0
    ports:
      - "3036:3036"
    volumes:
      - .:/var/app:cached
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/var/app/node_modules
    depends_on:
      - db
    command: bundle exec vite dev
