default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'db' } %>
  timeout: 5000
development:
  <<: *default
  database: job_tracker_development
test:
  <<: *default
  database: job_tracker_test
production:
  <<: *default
  database: job_tracker_production
